# Generated by Django 4.2.2 on 2023-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_listing_current_price_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
